# Generated by Django 6.0.3 on 2026-04-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(default='transaction', max_length=64),
            preserve_default=False,
        ),
    ]
