# Generated by Django 6.0.3 on 2026-05-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
